version: '3.1'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - asjorok-pg:/var/lib/postgresql/data
volumes:
  asjorok-pg:
